import type { Metadata } from "next";
import { Google_Sans_Flex } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { NotificationProvider } from "@/components/alert/NotificationProvider";
import Navbar from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { MIDTRANS_SNAP_URL } from "@/lib/midtrans-config";

const googleSansFlex = Google_Sans_Flex({
  variable: "--font-google-sans-flex",
  subsets: ["latin"],
  adjustFontFallback: false,
  fallback: ["system-ui", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Joyful",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${googleSansFlex.variable} min-h-screen h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Script
          src={MIDTRANS_SNAP_URL}
          data-client-key={process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
          strategy="afterInteractive"
        />
        <NotificationProvider>
          <Navbar />
          {children}
          <div className="progressive-blur"></div>
          <Footer />
        </NotificationProvider>
      </body>
    </html>
  );
}